### PR TITLE
acronym generator test collaboration

### PR DESCRIPTION
**Pull request by jumaantony**
This is a short python script to test collaboration. More projects are yet to be delivered.

### CODE REVIEW

**Review by Wahid7852 — APPROVED** [review]
Looks nice to me

**Review by 31Sanskrati — APPROVED** [review]
Thank you for contributing. I will merge the PR

**Comment by jumaantony** [comment]
Thank you. Which area in programming are you into?

Kind regards,
Juma Anton

**Comment by 31Sanskrati** [comment]
I am not mainly in any field right now. I am just a Student. Although I have studied Web dev, DevOps, and a bit of Cryptography on my own, I am currently working in Data Science.

**Pull request merged**
